export const PATIENT = "Patient"
export const VITALS = "Vitals"
export const HISTORY = "History"
export const SNELLENS_TEST = "Snellen's Test"
export const PRESENTING_COMPLAINTS = "Presenting Complaints"